# Variables
@baseUrl = http://localhost:3000

# Health check
GET {{baseUrl}}/health

### 

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Room name",
  "description": "Room description"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
  "question": "Question"
}