# Variables
@baseUrl = http://localhost:3000

# Health check
GET {{baseUrl}}/health

### 

# Get rooms
GET {{baseUrl}}/rooms

###

# Create room
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Room name",
  "description": "Room description"
}